name: Check Task

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Log Current Time
        run: echo "Cron job executed at $(date)"

      - name: Call API
        env:
          API_URL: ${{ secrets.CHECK_TASK_API }}
        run: |
          curl -X GET "$CHECK_TASK_API" -H "Content-Type: application/json"
