name: Create Task

on:
  schedule:
    - cron: "30 1 * * *" # Runs every day at 9:00 AM

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Log Current Time
        run: echo "Cron job executed at $(date)"

      - name: Call API
        env:
          API_URL: ${{ secrets.CREATE_TASK_API }}
        run: |
          curl -X POST "$API_URL" \
          -H "Content-Type: application/json" \
          -d '{"durationHours": 21}'
